# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c71c1f8380bc9302d42250234f8767a1c10f33c71bc741a5b2107aa15c3697ba43bb950ab10a3ae1cd3ee722b175f35d2344cba01df31eb6f37dbea55e00a70d

test:
  secret_key_base: 5f5cbe97fc938ff87a97593e24bcb2985721c657a6882ccbef4b27bc7a9f55531345493379928c1873718f73e0d05549d2af2946db0d5820eac6d45a6278fa5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
